name: infra_tools
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - erlang=27.3.4
  - ld_impl_linux-ppc64le=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - perl=5.32.1
  - pip=25.3
  - python=3.10.19
  - rabbitmq-server=4.2.2
  - readline=8.3
  - setuptools=80.9.0
  - socat=1.8.0.1
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.45.1
  - zlib=1.3.1
  - zstd=1.5.7
