name: ddmd_keras
channels:
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
  - defaults
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - absl-py=0.8.1
  - arrow-cpp=0.15.1
  - astor=0.8.0
  - blas=1.0
  - bokeh=1.4.0
  - boost-cpp=1.67.0
  - brotli=1.0.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2025.11.12
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=3.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - cryptography=35.0.0
  - cudatoolkit=10.2.89
  - cudf=0.11.0
  - cudnn=7.6.5_10.2
  - cuml=0.11.0
  - cupy=6.6.0
  - cython=0.29.24
  - cytoolz=0.11.0
  - dask=2.9.2
  - dask-core=2.9.2
  - dask-cuda=0.11.0
  - dask-cudf=0.11.0
  - distributed=2.9.3
  - dlpack=0.2
  - double-conversion=3.1.5
  - fastavro=0.22.7
  - fastrlock=0.4
  - freetype=2.11.0
  - fsspec=0.6.2
  - gast=0.2.2
  - gflags=2.2.2
  - glog=0.3.5
  - google-pasta=0.1.8
  - graphsurgeon=0.4.1
  - grpc-cpp=1.26.0
  - grpcio=1.16.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.8
  - jinja2=3.0.3
  - joblib=0.13.2
  - jpeg=9e
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - ld_impl_linux-ppc64le=2.45
  - libboost=1.67.0
  - libcudf=0.11.0
  - libcuml=0.11.0
  - libevent=2.1.8
  - libffi=3.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran-ng=7.3.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnvstrings=0.11.0
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - librmm=0.11.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.1.0
  - llvmlite=0.31.0
  - locket=0.2.1
  - lz4-c=1.8.1.2
  - markdown=3.1.1
  - markupsafe=2.0.1
  - msgpack-python=1.0.2
  - nccl=2.5.6
  - ncurses=6.5
  - numba=0.47.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - nvstrings=0.11.0
  - olefile=0.46
  - openssl=1.1.1w
  - opt_einsum=3.1.0
  - packaging=21.3
  - pandas=0.24.2
  - parquet-cpp=1.5.1
  - partd=1.2.0
  - pillow=7.1.2
  - pip=21.3.1
  - powerai-license=1.7.0
  - powerai-rapids=1.7.0
  - powerai-release=1.7.0
  - powerai-tools=1.7.0
  - protobuf=3.8.0
  - psutil=5.8.0
  - pyarrow=0.15.1
  - pycparser=2.21
  - pynvml=8.0.3
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.6.12
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2021.3
  - pyyaml=5.4.1
  - re2=2019.08.01
  - readline=8.2
  - rmm=0.11.0
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - setuptools=58.0.4
  - six=1.13.0
  - snappy=1.1.7
  - sortedcontainers=2.4.0
  - sqlite=3.38.2
  - tbb=2021.8.0
  - tblib=1.7.0
  - tensorboard=2.1.1
  - tensorflow=2.1.3
  - tensorflow-base=2.1.3
  - tensorflow-estimator=2.1.0
  - tensorflow-gpu=2.1.3
  - tensorrt=7.0.0.11
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - thrift-cpp=0.12.0
  - tk=8.6.11
  - toolz=0.11.2
  - tornado=6.1
  - uff=0.6.5
  - uriparser=0.9.3
  - urllib3=1.25.11
  - werkzeug=0.16.1
  - wheel=0.37.1
  - wrapt=1.11.2
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - apache-libcloud==3.7.0
      - biopython==1.79
      - black==22.8.0
      - cfgv==3.3.1
      - charset-normalizer==2.0.12
      - colorama==0.4.5
      - configparser==5.2.0
      - cycler==0.11.0
      - dataclasses==0.8
      - decorator==4.4.2
      - dill==0.3.4
      - distlib==0.4.0
      - docker-pycreds==0.4.0
      - filelock==3.4.1
      - flake8==5.0.4
      - gitdb==4.0.9
      - gitpython==3.1.18
      - gql==0.2.0
      - graphql-core==1.1
      - griddataformats==0.7.0
      - gsd==2.8.1
      - identify==2.4.4
      - importlib-metadata==4.2.0
      - importlib-resources==5.2.3
      - kiwisolver==1.3.1
      - matplotlib==3.3.4
      - mccabe==0.7.0
      - mdanalysis==2.0.0
      - mmtf-python==1.1.3
      - molecules==0.0.3.2
      - mrcfile==1.5.4
      - multiprocess==0.70.12.2
      - mypy-extensions==1.0.0
      - netifaces==0.11.0
      - networkx==2.5.1
      - nodeenv==1.6.0
      - ntplib==0.4.0
      - nvidia-ml-py3==7.352.0
      - parmed==3.0.0
      - parse==1.20.2
      - pathos==0.2.8
      - pathspec==0.9.0
      - platformdirs==2.4.0
      - pox==0.3.0
      - ppft==1.6.6.4
      - pre-commit==2.17.0
      - promise==2.3
      - pycodestyle==2.9.1
      - pydantic==1.9.2
      - pyflakes==2.5.0
      - python-dotenv==0.20.0
      - pyzmq==25.1.2
      - radical-entk==1.52.0
      - radical-gtod==1.52.0
      - radical-pilot==1.47.0
      - radical-saga==1.52.0
      - radical-utils==1.52.0
      - regex==2023.8.8
      - requests==2.27.1
      - sentry-sdk==1.9.0
      - setproctitle==1.2.3
      - shortuuid==1.0.13
      - simtk-unit==0.2
      - smmap==5.0.0
      - subprocess32==3.5.4
      - toml==0.10.2
      - tomli==1.2.3
      - tqdm==4.64.1
      - typed-ast==1.5.5
      - typing-extensions==4.1.1
      - virtualenv==20.16.2
      - wandb==0.9.7
      - watchdog==2.3.1
      - zipp==3.6.0
