name: /nobackup/projects/bddur53/nikjur/ppc64le/envs/ddmd_openmm
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cudatoolkit=10.2.89
  - cython=0.29.32
  - fftw=3.3.10
  - h5py=2.10.0
  - hdf5=1.10.6
  - joblib=1.3.2
  - keyutils=1.6.3
  - krb5=1.20.1
  - ld_impl_linux-ppc64le=2.45
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libzlib=1.2.13
  - ncurses=6.5
  - numpy=1.21.6
  - ocl-icd=2.3.3
  - ocl-icd-system=1.0.0
  - opencl-headers=2025.06.13
  - openmm=7.6.0
  - openssl=1.1.1w
  - pip=24.0
  - python=3.7.12
  - python_abi=3.7
  - pyyaml=5.4.1
  - readline=8.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=69.0.3
  - six=1.16.0
  - sqlite=3.46.0
  - threadpoolctl=3.1.0
  - tk=8.6.13
  - wheel=0.42.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - biopython==1.81
      - black==23.3.0
      - certifi==2025.11.12
      - cfgv==3.3.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - cycler==0.11.0
      - dill==0.3.7
      - distlib==0.4.0
      - filelock==3.12.2
      - flake8==5.0.4
      - fonttools==4.38.0
      - griddataformats==0.7.0
      - gsd==4.0.0
      - identify==2.5.24
      - idna==3.10
      - importlib-metadata==4.2.0
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - mccabe==0.7.0
      - mdanalysis==2.1.0
      - mdtools==0.1
      - mmtf-python==1.1.3
      - mrcfile==1.5.4
      - msgpack==1.0.5
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - netifaces==0.11.0
      - networkx==2.6.3
      - nodeenv==1.9.1
      - ntplib==0.4.0
      - packaging==24.0
      - parmed==4.0.0
      - pathos==0.3.1
      - pathspec==0.11.2
      - pillow==9.5.0
      - platformdirs==2.6.2
      - pox==0.3.3
      - ppft==1.7.6.7
      - pre-commit==2.21.0
      - psij-python==0.9.8
      - psutil==5.9.8
      - pycodestyle==2.9.1
      - pydantic==1.10.24
      - pyflakes==2.5.0
      - pyparsing==3.1.4
      - pystache==0.6.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==0.21.1
      - pyzmq==26.2.1
      - radical-entk==1.92.0
      - radical-gtod==1.90.0
      - radical-pilot==1.92.0
      - radical-utils==1.90.0
      - regex==2024.4.16
      - requests==2.31.0
      - setproctitle==1.3.3
      - tomli==2.0.1
      - tqdm==4.67.1
      - typed-ast==1.5.5
      - typeguard==4.1.2
      - typing-compat==0.1.0
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - virtualenv==20.16.2
      - zipp==3.15.0
